# Generated by Django 5.1.4 on 2024-12-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usuario_contraseña_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('usuario', 'Usuario')], max_length=15),
        ),
    ]
